default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_developtment

test: 
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  passowrd: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

